### ISSUE TITLE
grunt assemble:production fails with `Object has no method 'replace'` error

### ISSUE THREAD

**Issue by lfryc** [richwidgets/richwidgets#156]
``````
$ grunt dist --stack

Running "assemble:production" (assemble) task
JS-YAML: deficient indentation at line 19, column 1:
    ]
    ^
Assembling dist/demos/about.html OK
Assembling dist/demos/contributing.html OK
Assembling dist/demos/index.html OK
Assembling dist/demos/input/autocomplete.html ERROR
Warning: Object ```html
<input id="json-source" type="text" class="form-control" />

 has no method 'replace' Use --force to continue.
TypeError: Object ```html
<input id="json-source" type="text" class="form-control" />

 has no method 'replace'
    at Handlebars.Utils.escapeExpression (/mnt/workspace/workspaces/richfaces/widgets/richwidgets/node_modules/assemble/node_modules/assemble-handlebars/node_modules/handlebars/lib/handlebars/utils.js:51:19)
    at program11 (eval at <anonymous> (/mnt/workspace/workspaces/richfaces/widgets/richwidgets/node_modules/assemble/node_modules/assemble-handlebars/node_modules/handlebars/lib/handlebars/compiler/compiler.js:564:23), <anonymous>:119:10)
    at Object.fn (/mnt/workspace/workspaces/richfaces/widgets/richwidgets/node_modules/assemble/node_modules/assemble-handlebars/node_modules/handlebars/lib/handlebars/runtime.js:66:14)
    at Object.<anonymous> (/mnt/workspace/workspaces/richfaces/widgets/richwidgets/node_modules/assemble/node_modules/assemble-handlebars/node_modules/handlebars-helpers/lib/helpers/helpers-markdown.js:67:37)
    at program10 (eval at <anonymous> (/mnt/workspace/workspaces/richfaces/widgets/richwidgets/node_modules/assemble/node_modules/assemble-handlebars/node_modules/handlebars/lib/handlebars/compiler/compiler.js:564:23), <anonymous>:102:52)
    at /mnt/workspace/workspaces/richfaces/widgets/richwidgets/node_modules/assemble/node_modules/assemble-handlebars/node_modules/handlebars/lib/handlebars/runtime.js:59:17
    at Object.<anonymous> (/mnt/workspace/workspaces/richfaces/widgets/richwidgets/node_modules/assemble/node_modules/assemble-handlebars/node_modules/handlebars/lib/handlebars/base.js:100:21)
    at Object.eval (eval at <anonymous> (/mnt/workspace/workspaces/richfaces/widgets/richwidgets/node_modules/assemble/node_modules/assemble-handlebars/node_modules/handlebars/lib/handlebars/compiler/compiler.js:564:23), <anonymous>:185:25)
    at /mnt/workspace/workspaces/richfaces/widgets/richwidgets/node_modules/assemble/node_modules/assemble-handlebars/node_modules/handlebars/lib/handlebars/runtime.js:30:33
    at /mnt/workspace/workspaces/richfaces/widgets/richwidgets/node_modules/assemble/node_modules/assemble-handlebars/node_modules/handlebars/lib/handlebars/compiler/compiler.js:1274:21
    at Object.render (/mnt/workspace/workspaces/richfaces/widgets/richwidgets/node_modules/assemble/node_modules/assemble-handlebars/index.js:38:17)
    at Object.render (/mnt/workspace/workspaces/richfaces/widgets/richwidgets/node_modules/assemble/lib/engine/index.js:75:17)
    at build (/mnt/workspace/workspaces/richfaces/widgets/richwidgets/node_modules/assemble/tasks/assemble.js:571:23)
    at /mnt/workspace/workspaces/richfaces/widgets/richwidgets/node_modules/assemble/tasks/assemble.js:387:9
    at Array.forEach (native)
    at Array.renderPages [as 5] (/mnt/workspace/workspaces/richfaces/widgets/richwidgets/node_modules/assemble/tasks/assemble.js:383:30)
    at next (/mnt/workspace/workspaces/richfaces/widgets/richwidgets/node_modules/assemble/lib/assemble.js:78:22)
    at Array.assemblePages [as 4] (/mnt/workspace/workspaces/richfaces/widgets/richwidgets/node_modules/assemble/tasks/assemble.js:376:7)
    at next (/mnt/workspace/workspaces/richfaces/widgets/richwidgets/node_modules/assemble/lib/assemble.js:78:22)
    at Array.assembleData [as 3] (/mnt/workspace/workspaces/richfaces/widgets/richwidgets/node_modules/assemble/tasks/assemble.js:201:7)
    at next (/mnt/workspace/workspaces/richfaces/widgets/richwidgets/node_modules/assemble/lib/assemble.js:78:22)
    at Array.assemblePartials [as 2] (/mnt/workspace/workspaces/richfaces/widgets/richwidgets/node_modules/assemble/tasks/assemble.js:155:7)
    at next (/mnt/workspace/workspaces/richfaces/widgets/richwidgets/node_modules/assemble/lib/assemble.js:78:22)
    at Array.assembleDefaultLayout [as 1] (/mnt/workspace/workspaces/richfaces/widgets/richwidgets/node_modules/assemble/tasks/assemble.js:113:7)
    at next (/mnt/workspace/workspaces/richfaces/widgets/richwidgets/node_modules/assemble/lib/assemble.js:78:22)
    at Array.optionsConfiguration [as 0] (/mnt/workspace/workspaces/richfaces/widgets/richwidgets/node_modules/assemble/tasks/assemble.js:94:7)
    at Object.build (/mnt/workspace/workspaces/richfaces/widgets/richwidgets/node_modules/assemble/lib/assemble.js:74:18)
    at Object.<anonymous> (/mnt/workspace/workspaces/richfaces/widgets/richwidgets/node_modules/assemble/tasks/assemble.js:420:8)
    at Object.<anonymous> (/mnt/workspace/workspaces/richfaces/widgets/richwidgets/node_modules/grunt/lib/grunt/task.js:258:15)
    at Object.thisTask.fn (/mnt/workspace/workspaces/richfaces/widgets/richwidgets/node_modules/grunt/lib/grunt/task.js:78:16)
    at Object.<anonymous> (/mnt/workspace/workspaces/richfaces/widgets/richwidgets/node_modules/grunt/lib/util/task.js:282:30)
    at Task.runTaskFn (/mnt/workspace/workspaces/richfaces/widgets/richwidgets/node_modules/grunt/lib/util/task.js:235:24)
    at Task.<anonymous> (/mnt/workspace/workspaces/richfaces/widgets/richwidgets/node_modules/grunt/lib/util/task.js:281:12)
    at Task.<anonymous> (/mnt/workspace/workspaces/richfaces/widgets/richwidgets/node_modules/grunt/lib/util/task.js:215:7)
    at Task.runTaskFn (/mnt/workspace/workspaces/richfaces/widgets/richwidgets/node_modules/grunt/lib/util/task.js:238:9)
    at Task.<anonymous> (/mnt/workspace/workspaces/richfaces/widgets/richwidgets/node_modules/grunt/lib/util/task.js:281:12)
    at Task.<anonymous> (/mnt/workspace/workspaces/richfaces/widgets/richwidgets/node_modules/grunt/lib/util/task.js:215:7)
    at Task.runTaskFn (/mnt/workspace/workspaces/richfaces/widgets/richwidgets/node_modules/grunt/lib/util/task.js:238:9)
    at Task.<anonymous> (/mnt/workspace/workspaces/richfaces/widgets/richwidgets/node_modules/grunt/lib/util/task.js:281:12)
    at Task.<anonymous> (/mnt/workspace/workspaces/richfaces/widgets/richwidgets/node_modules/grunt/lib/util/task.js:215:7)
    at null._onTimeout (/mnt/workspace/workspaces/richfaces/widgets/richwidgets/node_modules/grunt/lib/util/task.js:225:33)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
``````

**Comment by lfryc** [comment]
The error can be resolved by upgrade to assemble 0.4.31
